- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20221126212641035400000010.cgzl7oifc3ym.us-east-1.rds.amazonaws.com" 
    login_user: "dapetoo"
    login_password: "d134apetooVSQ"
    name: wordpressdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input wordpress credentials
  ansible.builtin.replace:
    path: /var/www/html/wp-config.php 
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^localhost', line: "terraform-20221126212641035400000010.cgzl7oifc3ym.us-east-1.rds.amazonaws.com" }
    - { regexp: '^username_here', line: "dapetoo" }
    - { regexp: '^database_name_here', line: "wordpressdb" }
    - { regexp: '^password_here', line: "d134apetooVSQ" }
