---

name: Packer

on:
  push:
    branches:
      - terraform-cloud

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Change directory
        run: export AWS_ACCESS_KEY_ID=${{ secrets.aws_access_key_id }} && export AWS_ACCESS_KEY_ID=${{ secrets.aws_secret_access_key }}
      - name: Install Packer
        run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - && sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && sudo apt-get update && sudo apt-get install -y packer
      - name: Packer initialization
        run: cd AMI/ && packer init bastion.pkr.hcl && packer init nginx.pkr.hcl && packer init ubuntu.pkr.hcl && packer init web.pkr.hcl
      - name: Packer Build
        run: cd AMI/ && packer build bastion.pkr.hcl && packer build nginx.pkr.hcl && packer build ubuntu.pkr.hcl && packer build web.pkr.hcl