---

name: Packer

on:
  push:
    branches:
      - terraform-cloud
    paths:
      - packer/**
      - .github/workflows/packer.yml

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Change directory
        run: cd AMI && ls -al
      # fix backwards incompatibilities in template
      # - name: Fix Template
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: fix

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: bastion.pkr.hcl nginx.pkr.hcl ubuntu.pkr.hcl web.pkr.hcl
          # working_directory: infrastructure/packer
        env:
          PACKER_LOG: 1
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}

      # additional steps to process artifacts