---

name: Packer

on:
  push:
    branches:
      - terraform-cloud

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Change directory
        run: cd AMI && ls -al
      - name: Install Packer
        run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - && sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && sudo apt-get update && sudo apt-get install -y packer
      - name: Packer initialization
        run: cd AMI/ && packer init bastion.pkr.hcl && packer init nginx.pkr.hcl && packer init ubuntu.pkr.hcl && packer init web.pkr.hcl
      # # build artifact
      # - name: Initialize
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: init
      #     arguments: "-color=false -on-error=abort"
      #     target: bastion.pkr.hcl nginx.pkr.hcl ubuntu.pkr.hcl web.pkr.hcl
      #     working_directory: AMI

      # # validate templates
      # - name: Validate Template
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: validate
      #     working_directory: AMI/
      #     arguments: -syntax-only
      #     target: bastion.pkr.hcl nginx.pkr.hcl ubuntu.pkr.hcl web.pkr.hcl

      # # build artifact
      # - name: Build Artifact
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: build
      #     arguments: "-color=false -on-error=abort"
      #     target: bastion.pkr.hcl nginx.pkr.hcl ubuntu.pkr.hcl web.pkr.hcl
      #     working_directory: AMI/
      #   env:
      #     PACKER_LOG: 1
      #     HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
      #     HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}

      # # additional steps to process artifacts